[workspace]
members = ["days/*"]

[workspace.package]
version = "0.25.0"
authors = ["Nick Ruha"]
description = "Advent of code"


[profile.release]
lto = true
codegen-units = 1
strip = true  # Automatically strip symbols from the binary.
# opt-level = "z"  # Optimize for size.
